# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_remove_profile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_first_name', models.CharField(max_length=300)),
                ('proxy_phone_number', models.CharField(default='Enter the your proxy user phone number', max_length=14)),
                ('is_registered_to_kongapay', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='Enter password', max_length=100),
        ),
    ]
