# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170319_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='proxy_last_name',
            field=models.CharField(default='pln', max_length=300),
        ),
        migrations.AlterField(
            model_name='orders',
            name='proxy_first_name',
            field=models.CharField(default='pfn', max_length=300),
        ),
    ]
